### ISSUE TITLE
Support for APIRouter

### ISSUE THREAD

**Issue by tisboyo** [codemation/easyauth#1]
Would it be possible to support using with APIRouter for route files?

**Comment by codemation** [comment]
@tisboyo this should be possible by extending an EasyAuthClient with a .create_api_router factory method which accepts all the same parameters for instantiating a FastAPI APIRouter, and and then automatically includes the router and returns as a wrapped auth router. 

A nice addition, so I'll add to the next release.

**Comment by codemation** [comment]
https://pypi.org/project/easy-auth/0.126/ - released! 

Check the syntax and make sure the usage is clear, and feel free to close this issue.

**Comment by tisboyo** [comment]
That works great!
