### ISSUE TITLE
Since db_proxy.py is being written to on every startup, it causes uvicorn to auto restart in an endless loop when reload=True.

### ISSUE THREAD

**Issue by codemation** [codemation/easyauth#10]
Also since db_proxy.py is being written to on every startup, it causes uvicorn to auto restart in an endless loop when reload=True.

_Originally posted by @tisboyo in https://github.com/codemation/easyauth/issues/4#issuecomment-832358421_

**Comment by codemation** [comment]
Another good catch @tisboyo

Programatically starting the child processes for db_proxy & manager_proxy, requires a predictable path, creating in place was a quick win, but the best solution is to use the library path, and determine via the following:
```python
>>> import sys
>>> sys.path
['', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/easyauth/tests/test-env/lib/python3.8/site-packages']
```
Solution:

- [ ] Remove file generation at startup & include prepared version with installed library. 
- [ ] Refactor proxies to use site-packages from sys.path + easyauth, to determine location of proxies to start

**Comment by codemation** [comment]
sys.path fix was not required for fix as gunicorn can directly reference libraries in site-packages, removing requirement for generating files & path detection. 

Fix for reload available in release:
https://pypi.org/project/easy-auth/0.138/

@tisboyo - let me know how that works for you.

**Comment by tisboyo** [comment]
Well this one didn't start until this update, not sure it's 100% related but i'll put it here.
So on startup, in the console I get 

> 05-09 14:55 wsRpc-proxy  WARNING  creating cron or get_all_registered_functions - interval 30
> 05-09 14:55 wsRpc-proxy  ERROR    error during _cron_refresh_tables - IndexError('function show_tables not found')
> 05-09 14:55 wsRpc-proxy  ERROR    error with proxy_request

Then I get a traceback ending in

>   File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 528, in _sock_connect_cb
>     raise OSError(err, f'Connect call failed {address}')
> ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 8091)

Then of course causing a cascade of other errors. But ultimately it's trying to open a connection to 8091 and failing, then causing uvicorn to exit.

**Comment by codemation** [comment]
Hey @tisboyo , that is a fairly common series of exceptions when quorum DB is not empty. Try to delete & restart:
```
rm quorum
```

I am still working on an better way of resetting this db file, if existing, but it must be a DB and not a simple lock.txt file due to the checks required when multiple EasyAuthServer workers are used & a leader must be elected.

**Comment by tisboyo** [comment]
@codemation have been busy with other things, probably won't get back to this until the weekend. Will update as soon as I can

**Comment by tisboyo** [comment]
Looks like this one is good to go!

**Comment by tisboyo** [comment]
and, github is being weird, I can't close the issue for some reason.

**Comment by codemation** [comment]
@tisboyo  thanks for confirming and for your contributions!
