### ISSUE TITLE
docker entrypoint file

### ISSUE THREAD

**Issue by Turall** [codemation/easyauth#11]
hi, thanks for this project. I want to run  this project in  docker , but I get an error. 
``` 
docker run --name easyauth \
    -e DB_TYPE=sqlite \
    -e DB_NAME=auth \
    -e DB_LOCAL_PATH=/mnt/easyauth \
    -e ISSUER=EasyAuth \
    -e SUBJECT=EasyAuthAuth \
    -e AUDIENCE=EasyAuthApis \
    -e KEY_PATH=/mnt/easyauth \
    -e KEY_NAME=test_key \
    -v $(pwd)/easyauth-vol:/mnt/easyauth \
    -p 8220:8220 \
    -d joshjamison/easyauth:v0.0.0

./entrypoint.sh: line 3: gunicorn: command not found

**Comment by tisboyo** [comment]
I also noticed this a few days ago when i was considering splitting off the server.

**Comment by codemation** [comment]
@Turall - glad that you are enjoying it, and good catch. I am updating the docker server instance & usage docs with latest changes. Update coming soon! 

- [ ]  update docker image with latest easyauth dependency & setup changes
- [ ]  update docs with latest docker usage instructions

**Comment by codemation** [comment]
@Turall  & @Turall - check docs [here](https://easyauth.readthedocs.io/en/latest/server_usage/#docker) for latest instructions. 

Added updated docker image with following tags:
- joshjamison/easyauth:v0.0.1
- joshjamison/easyauth:latest

Let me know how it goes

**Comment by Turall** [comment]
> @Turall & @Turall - check docs [here](https://easyauth.readthedocs.io/en/latest/server_usage/#docker) for latest instructions.
> 
> Added updated docker image with following tags:
> 
> * joshjamison/easyauth:v0.0.1
> * joshjamison/easyauth:latest
> 
> Let me know how it goes
Worked, thank you!

**Comment by codemation** [comment]
Thanks for closing @Turall  and for your report / contribution.
