### ISSUE TITLE
EasyAuthClient cannot connect to server using wildcard address

### ISSUE THREAD

**Issue by shazz** [codemation/easyauth#12]
When the client is configured using `0.0.0.0` to access the server, the following error occurs from the fastAPI authorize widget:

````
Auth ErrorTypeError: Failed to fetch
````

If the wildcard addresss is replaced by the server "real" IP address it works,

**Comment by codemation** [comment]
I have not been able to reproduce this. @shazz  let me know if you ran into any new issues on latest releases. Closing for now.
