### ISSUE TITLE
Identity Provider: Google

### ISSUE THREAD

**Issue by jasonvriends** [codemation/easyauth#26]
Wouldn't you need to have the ability to specify the client secret also?

**Comment by codemation** [comment]
@jasonvriends - a feature of easyauth and google authentication is that only client_id is needed. The CLIENT_ID provides a user with the means of creating an identity token, this id token can be verified without a client secret using library google.oauth2 method [id_token](https://github.com/codemation/easyauth/blob/23953e172a6a84f0a69cd8a859243d09bbccc1c5/easyauth/server.py#L667)
