### ISSUE TITLE
Feature Request: Create user via API without authentication

### ISSUE THREAD

**Issue by jasonvriends** [codemation/easyauth#28]
Creating user manually or allowing users to create their own account via the /admin page works perfect. Let's say we create a front end to our FastAPI application and need the ability to create a new user. If we call http://0.0.0.0:8330/auth/user to create a user from the frontend this requires authentication. Ideally, creating a new user wouldn't require authentication so that it can be done via another frontend.

**Comment by codemation** [comment]
Every Client should have a /register - GET - endpoint automatically, which allows them to create users. Do you need to implement your own register page? If so you would need to ensure a JSON body is sent to a POST /register on the client matching the same form sent from the the default client /register - GET 

see [here](https://github.com/codemation/easyauth/blob/23953e172a6a84f0a69cd8a859243d09bbccc1c5/easyauth/client.py#L197) 

Let me know if this helps

**Comment by jasonvriends** [comment]
Perfect. The label for /auth/user indicated it was the create user API but now that makes sense. /register would call /auth/user.

**Comment by codemation** [comment]
@jasonvriends if no other questions, close this when possible.
