### ISSUE TITLE
Status code error in client

### ISSUE THREAD

**Issue by tisboyo** [codemation/easyauth#3]
https://github.com/codemation/easyauth/blob/618b2896d7a5e34c59f184e233f9f6379e84c890/easyauth/client.py#L118

I imagine this should be HTTP_302_FOUND.

**Comment by codemation** [comment]
Absolutely, good catch.

**Comment by codemation** [comment]
Fixed in https://pypi.org/project/easy-auth/0.129/ - thanks @tisboyo
