### ISSUE TITLE
Editing service in admin not working

### ISSUE THREAD

**Issue by akyl0221** [codemation/easyauth#56]
When edit service in admin server return 404 Not Found {"detail": "no user with name {service} exists"}

**Comment by codemation** [comment]
Thanks for opening the issue. I will have a look at this when I have some more time. Similar to #55 , feel free to fork, fix & create a PR.

**Comment by akyl0221** [comment]
Ok I will do it

**Comment by codemation** [comment]
Fixed in https://github.com/codemation/easyauth/releases/tag/1.0.20 - nice work @akyl0221
