### ISSUE TITLE
Where I found the GUI link and how to install it

### ISSUE THREAD

**Issue by rituranjan** [codemation/easyauth#61]
Where I found the GUI link and how to install it

**Comment by codemation** [comment]
@rituranjan 

I would suggest reviewing:
- https://medium.com/itnext/creating-secure-apis-with-easyauth-fastapi-6996a5e42d07
- https://medium.com/itnext/add-google-login-to-a-fastapi-app-with-easyauth-c8c3e926ad0a
- https://easyauth.readthedocs.io/en/latest/

Let me know if you have specific problems / questions.
