### ISSUE TITLE
Hi I am window 10 user unable to install easy auth client/server  so please help me& how to install with docker

### ISSUE THREAD

**Issue by rituranjan** [codemation/easyauth#62]
raise RuntimeError('uvloop does not support Windows at the moment')
      RuntimeError: uvloop does not support Windows at the moment
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

**Comment by codemation** [comment]
Hello @rituranjan , thanks for opening this issue, I think uvloop is not a required dependency and can be removed from the required list. I will test / verify & remove soon.

**Comment by codemation** [comment]
Fixed in https://github.com/codemation/easyauth/releases/tag/1.0.20  - check again and let me know if there is the same issue.
