### ISSUE TITLE
"401 Unauthorized" when logging to admin account

### ISSUE THREAD

**Issue by pedrocavadas** [codemation/easyauth#76]
I followed all instructions regarding installation and starting an EasyAuth server, but when trying to log in to "/admin" with the "admin" account that is automatically created when launching the server for the first time, I get error "401 Unauthorized". Any idea of what can be happening?

**Comment by pedrocavadas** [comment]
That's the issue, when using username "admin" with this generated password, I get the "401 Unauthorized" error, and the log in page doesn't redirect me anywhere.

**Comment by codemation** [comment]
Do you see the same result from the /docs login?

**Comment by pedrocavadas** [comment]
![image](https://user-images.githubusercontent.com/43155616/207631252-b8f29605-1757-48e9-9758-ab79b2cac923.png)

**Comment by codemation** [comment]
Not sure if you have the order that reproduces this from the GUI. My theory is that you are directly browsing to `/login`, which prompts login and creates the cookie, but does not redirect because there is no ref to redirect to. If you first browsed to `/admin/users` for instance without being login, you would be redirected to `/login`, which after successful should redirect you back to `/admin/users`. 

If this assumption is not correct, please list the exact steps to reproduce and I will look deeper into this.

**Comment by pedrocavadas** [comment]
Well, I tried three different endpoints: <my_ip_address>:<my_port>/admin, <my_ip_address>:<my_port>/admin/users and <my_ip_address>:<my_port>/login. On these three tries, I got error "401 Unauthorized", and the GUI didn't redirect me anywhere, staying on the login page.

Steps to reproduce:
1. Start server via command-line: "uvicorn --host 0.0.0.0 --port 18124 test_server:server"
2. Get the default admin password outputted in the logs
3. Go to <my_ip_address>:<my_port>/admin
4. Type username "admin" and the password from step 2
5. Click "Login"
6. My issue happens

**Comment by codemation** [comment]
Looks like a new issue with set cookie not working. I reproduced locally as well in a new env, will fix ASAP.

**Comment by codemation** [comment]
This should be fixed in latest release. https://github.com/codemation/easyauth/releases/tag/1.0.27 

Let me know if you run into anything new. Thanks for reporting.

**Comment by pedrocavadas** [comment]
It works! Thank you so much.

**Comment by singlautsav** [comment]
`INFO:     127.0.0.1:64085 - "GET /admin/ HTTP/1.1" 401 Unauthorized
INFO:     127.0.0.1:64103 - "GET /admin/ HTTP/1.1" 401 Unauthorized
INFO:     127.0.0.1:64103 - "GET /admin/ HTTP/1.1" 401 Unauthorized
INFO:     127.0.0.1:64103 - "GET /admin/ HTTP/1.1" 401 Unauthorized
INFO:     127.0.0.1:64103 - "GET /admin/ HTTP/1.1" 401 Unauthorized
INFO:     127.0.0.1:64103 - "GET /login HTTP/1.1" 200 OK
INFO:     127.0.0.1:64103 - "POST /login HTTP/1.1" 302 Found
07-23 23:30 EasyRpc-server /ws/manager WARNING  global_store_update - update - tokens - c91ae036-03af-4562-89e8-cb635bb30a17
INFO:     127.0.0.1:64103 - "GET /admin/ HTTP/1.1" 401 Unauthorized`

Getting the same issue where I am unable to login on the frontend with the admin/password generated. While I can do the same on the docs pages.

**Comment by codemation** [comment]
@singlautsav - it would help if you create a new issue. Ideally with steps to reproduce the problem and a snapshot of your environment i.e `pip freeze` & basic code example that you observe the issue.

**Comment by singlautsav** [comment]
@codemation raised as new issue https://github.com/codemation/easyauth/issues/105
