### ISSUE TITLE
"/groups" not working

### ISSUE THREAD

**Issue by pedrocavadas** [codemation/easyauth#79]
Hi! After the update, I managed to get my test server and client working, so I tried creating a test service to check if I could make the requests properly, but stumbled across the error "{"detail":"not authorized, permissions required: {'groups': ['users', 'admins']}"}" when trying the /groups endpoint. It's probably some mistake on my side, so I was wondering if anyone could help me out.

Here are the steps I followed:
1. Start both test server and client
2. Create a service named "test service"
3. Assign "test service" to "administrators" group
4. Generate a token for "test service"
5. Grab the token generated and insert it on the request header: curl -X GET http://<my_ip_address>:<my_port>/groups -H 'Content-Type: application/json' -H 'Authorization: Bearer <test_service_token>' 

Am I missing something?

**Comment by codemation** [comment]
The error indicates the problem I think:
```bash
"{"detail":"not authorized, permissions required: {'groups': ['users', 'admins']}"}"
```
The route was probably decorated with groups=["users", "admins"], if you want to allow access, then "administrators" needs to be in the the decorated list as well.

**Comment by codemation** [comment]
@pedrocavadas solve your problem?

**Comment by pedrocavadas** [comment]
Sorry, I forgot to reply here. Yes, it did solve it, thank you sou much.
