### ISSUE TITLE
Python tool without service account

### ISSUE THREAD

**Issue by remydewa** [codemation/easyauth#93]
Hello,

I want to know how can I have a python tools which give me access to my authenticated api without creating a service account. 

Actually, what I'm trying to do:
```
req_header = {
        "Content-Type": "application/json"
    }

    req_body = {
            "username": "myuser",
            "password": "xxxx"
    }

resp = requests.post(
        "http://127.0.0.1:5858/auth/token",
        headers=req_header,
        json=req_body,
        verify=False
    )
```
The goal below is to get a token to access to my other api but it doesn't works:

{'detail': [{'loc': ['body', 'username'], 'msg': 'field required', 'type': 'value_error.missing'}, {'loc': ['body', 'password'], 'msg': 'field required', 'type': 'value_error.missing'}]}

What Am it doing wrong?

Thanks for your help

Rémy

**Comment by codemation** [comment]
Hey @remydewa,

There are a few examples of how token is exchanged for credentials in tests [here](https://github.com/codemation/easyauth/blob/89e958cdb719050795bf869f56d003bc5cf25e64/tests/test_server_api.py#L28) 

Looks like you are just missing the `/login` in front of `auth/token`, -> `auth/token/login`

**Comment by remydewa** [comment]
Hey @codemation 

Thanks for your answer. It's working well! My bad. Sorry.

Good evening

Rémy
